highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://seanmangar.github.io/vitae
author: Sean Mangar

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Sean Mangar's Resume
name: Sean Mangar
email: sean@bitfuel.io
email_full: mailto:sean@bitfuel.io
website: seanmangar.com
website_full: http://seanmangar.com
github: seanmangar
twitter: seanmangar
address: 101, Prince of Wales Street
city: Rose Hill
country: Mauritius
google_analytics: UA-73116983-6

# needed for travis-ci build
exclude: [vendor]
